name: Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create a release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Zip files excluding unwanted items
      - name: Create release artifact
        run: |
          mkdir release
          rsync -av --progress . ./release --exclude src --exclude package.json --exclude webpack.config.js
          cd release
          zip -r ../release-${{ github.ref_name }}.zip ./
          cd ..

      # Upload the zip as release asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release-${{ github.ref_name }}.zip
          asset_name: release-${{ github.ref_name }}.zip
          asset_content_type: application/zip
